### ISSUE TITLE
Missing wifi drivers (T14s) Qualcomm

### ISSUE THREAD

**Issue by lkocman** [agama-project/agama#1756]
Simiar to #1752 we seem to be lacking WiFi drivers that were previously present in installation-images. 

https://github.com/openSUSE/installation-images/blob/fd8629fc4b4b5810b668881fa430c30cc81056f3/obs/installation-images.spec#L520

**Comment by lkocman** [comment]
Interestingly no issues on T495, and our Tuxedo.

**Comment by lkocman** [comment]
I suppose we need to add firmware for Qualcomm Atheros

lkocman@localhost:~> rpm -qa | grep firmware | grep ath
kernel-firmware-ath12k-20240728-150600.3.6.1.noarch
kernel-firmware-atheros-20240728-150600.3.6.1.noarch
kernel-firmware-ath11k-20240728-150600.3.6.1.noarch
kernel-firmware-ath10k-20240728-150600.3.6.1.noarch

**Comment by lkocman** [comment]
But I don't see any of these here https://github.com/openSUSE/installation-images/blob/fd8629fc4b4b5810b668881fa430c30cc81056f3/obs/installation-images.spec#L586

**Comment by lslezak** [comment]
No, that's not a problem. We use `kernel-firmware` which is a bundle of all firmware packages. The `kernel-firmware-ath11k` and others are the split versions, they actually conflict with the `kernel-firmware` we use.

The real problem is that that the kernel modules in this case use wildcards to specify the firmware files, e.g. `ath11k/WCN6855/hw2.1/*`. Unfortunately the script which cleans up the unused firmware uses that as a raw file name without expansion and that does not match.

Another problem is that some firmware uses symlinks, again the script does not check it and it can potentially delete the symlink target if it is not referenced elsewhere and the result is dangling symlink.

I'll fix both problems....

**Comment by lslezak** [comment]
Fixed in #1812
